build_root:
  project_image:
    dockerfile_path: openshift/ci-operator/build-image/Dockerfile
promotion:
  additional_images:
    serverless-operator-src: src
  namespace: openshift
  tag: main
resources:
  '*':
    requests:
      cpu: 500m
      memory: 1Gi
tests:
- as: test-all-e2e-aws-ocp-412
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  steps:
    allow_best_effort_post_steps: true
    post:
    - as: knative-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --image=quay.io/openshift-knative/must-gather --dest-dir
        "${ARTIFACT_DIR}/gather-knative"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    - as: openshift-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --dest-dir "${ARTIFACT_DIR}/gather-openshift"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    test:
    - as: test
      cli: latest
      commands: make test-all-e2e
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 4h0m0s
    workflow: generic-claim
- as: test-all-e2e-aws-ocp-412-continuous
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  cron: 0 0,12 * * *
  steps:
    allow_best_effort_post_steps: true
    post:
    - as: knative-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --image=quay.io/openshift-knative/must-gather --dest-dir
        "${ARTIFACT_DIR}/gather-knative"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    - as: openshift-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --dest-dir "${ARTIFACT_DIR}/gather-openshift"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    test:
    - as: test
      cli: latest
      commands: make test-all-e2e
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 4h0m0s
    workflow: generic-claim
- as: test-e2e-aws-ocp-412
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  steps:
    allow_best_effort_post_steps: true
    post:
    - as: knative-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --image=quay.io/openshift-knative/must-gather --dest-dir
        "${ARTIFACT_DIR}/gather-knative"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    - as: openshift-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --dest-dir "${ARTIFACT_DIR}/gather-openshift"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    test:
    - as: test
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 4h0m0s
    workflow: generic-claim
- as: test-e2e-aws-ocp-412-continuous
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  cron: 0 0,12 * * *
  steps:
    allow_best_effort_post_steps: true
    post:
    - as: knative-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --image=quay.io/openshift-knative/must-gather --dest-dir
        "${ARTIFACT_DIR}/gather-knative"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    - as: openshift-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --dest-dir "${ARTIFACT_DIR}/gather-openshift"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    test:
    - as: test
      cli: latest
      commands: make test-e2e
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 4h0m0s
    workflow: generic-claim
- as: test-kitche-4f58f1a-aws-ocp-412
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  steps:
    allow_best_effort_post_steps: true
    post:
    - as: knative-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --image=quay.io/openshift-knative/must-gather --dest-dir
        "${ARTIFACT_DIR}/gather-knative"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    - as: openshift-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --dest-dir "${ARTIFACT_DIR}/gather-openshift"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    test:
    - as: test
      cli: latest
      commands: make test-kitchensink-e2e
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 4h0m0s
    workflow: generic-claim
- as: test-kitche-4f58f1a-aws-ocp-412-continuous
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  cron: 0 0,12 * * *
  steps:
    allow_best_effort_post_steps: true
    post:
    - as: knative-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --image=quay.io/openshift-knative/must-gather --dest-dir
        "${ARTIFACT_DIR}/gather-knative"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    - as: openshift-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --dest-dir "${ARTIFACT_DIR}/gather-openshift"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    test:
    - as: test
      cli: latest
      commands: make test-kitchensink-e2e
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 4h0m0s
    workflow: generic-claim
- as: test-ui-e2e-aws-ocp-412
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  steps:
    allow_best_effort_post_steps: true
    post:
    - as: knative-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --image=quay.io/openshift-knative/must-gather --dest-dir
        "${ARTIFACT_DIR}/gather-knative"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    - as: openshift-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --dest-dir "${ARTIFACT_DIR}/gather-openshift"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    test:
    - as: test
      cli: latest
      commands: make test-ui-e2e
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 4h0m0s
    workflow: generic-claim
- as: test-ui-e2e-aws-ocp-412-continuous
  cluster_claim:
    architecture: amd64
    cloud: aws
    owner: openshift-ci
    product: ocp
    timeout: 1h0m0s
    version: "4.12"
  cron: 0 0,12 * * *
  steps:
    allow_best_effort_post_steps: true
    post:
    - as: knative-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --image=quay.io/openshift-knative/must-gather --dest-dir
        "${ARTIFACT_DIR}/gather-knative"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    - as: openshift-must-gather
      best_effort: true
      cli: latest
      commands: oc adm must-gather --dest-dir "${ARTIFACT_DIR}/gather-openshift"
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 20m0s
    test:
    - as: test
      cli: latest
      commands: make test-ui-e2e
      from: src
      resources:
        requests:
          cpu: 100m
      timeout: 4h0m0s
    workflow: generic-claim
zz_generated_metadata:
  branch: main
  org: openshift-knative
  repo: serverless-operator
  variant: "412"
